name: Collect CityBikes Data
on:
  workflow_dispatch:
  
concurrency:
  group: citybikes-job
  cancel-in-progress: false
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install pandas requests gspread google-auth
      - name: Run script
        uses: nick-fields/retry@v3
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 15
          retry_on: error
          command: python script.py
      - name: Update and commit script.py
        run: |
          # Add or update a timestamp comment at top of file
          sed -i "1s|^# Last run:.*|# Last run: $(date -u)|; 1t; 1i # Last run: $(date -u)" script.py
          git config --global user.name "adrianjuliusaluoch"
          git config --global user.email "adrianjuliusaluoch@gmail.com"
          git add script.py
          git commit -m "Keep workflow alive [skip ci]" || echo "No changes to commit"
          git pull --rebase origin main
          git push
        continue-on-error: true
