name: Fetch Fares
on:
  workflow_dispatch:
concurrency:
  group: guardian-fares-job
  cancel-in-progress: false
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install pandas requests gspread google-auth
      - name: Run script
        uses: nick-fields/retry@v3
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 15
          retry_on: error
          command: python guardian.py
